# -*- coding: utf-8 -*-
"""[백준]Python 이진수 변환.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XatA8jhR8_k9QxMsfLVukd1ELBv9MEJr
"""

a=bin(int(input()))[2:]
print(a)