# -*- coding: utf-8 -*-
"""[백준]Python 팩토리얼.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XatA8jhR8_k9QxMsfLVukd1ELBv9MEJr
"""

def a(n):
  if n==0:
    return 1
  else:
    return n*a(n-1)
n=int(input())
a(n)