# -*- coding: utf-8 -*-
"""복습#5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SPNcvzOBATc3VRUF7xTUSCj7CzIIO-T4
"""

import pandas as pd
url='https://raw.githubusercontent.com/TeamLab/machine_learning_from_scratch_with_python/master/code/ch12/titanic/train.csv'
tit=pd.read_csv(url)
tit

tit.info()

tpa=tit[['Pclass','Age']]
tas=tit[['Age','Survived']]

tpa.plot.scatter(x='Pclass',y='Age')

tas.plot.bar(x='Age',y='Survived')

