# -*- coding: utf-8 -*-
"""복습#1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14ALtQbpoBuqTDNIqOBj7mZ-h14FDdPEQ
"""

#로또번호 생성
import random
lotto=[int(random.random()*45+1) for i in range(6)]
lotto2={int(random.randint(1,45)) for i in range(6)}

lotto2

lotto.sort()

lotto

list(lotto2).sort()



사람='가위'
컴=random.randint(1,3)
li=['가위','바위','보']
컴 = li[random.randint(0,2)]
print('승') if 컴=='보' else print('패') if 컴=='바위' else print('무')

컴

컴=random.choice(['가위','바위','보'])

컴

l=random.sample([i+1 for i in range(45)],6)

sorted(l)

random.sample(range(1,46),6)

# Commented out IPython magic to ensure Python compatibility.
## 매직 명령어
# %whos

dan =3
l=[dan* i for i in range(1,10)]
print(l)

l

for i in range(1,10):
  print(str(dan)+' * '+str(i)+' = '+str(dan*i))

l=[str(dan)+'*'+str(i)+'='+str(dan*i) for i in range(1,10)]

print(l)

for i in range(2,10):
  print("***",i,"단***")
  for j in range(1,10):
    print(i,"*",j,"=",i*j)

shirt

total=0
l=1
while l<1001:
  if l%3==0:
    total+=l
  l+=1
print(total)

y=0
while y<6:
  print("*"*y)
  y+=1

for i in range(1,101):
  print(i)

a=[70, 60, 55, 75, 95, 90, 80, 80, 85, 100]
x=0
for i in a:
  x+=i
x/len(a)

numbers=[1,2,3,4,5]
result=[n*2 for n in numbers if n%2==1]

# Commented out IPython magic to ensure Python compatibility.
# %whos

# Commented out IPython magic to ensure Python compatibility.
# %%writefile

