# -*- coding: utf-8 -*-
"""[백준] Python 팩토리얼 진법

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_x4yd7flkNsOorjjbiDtvgpwsx6AGy3K
"""

import sys

def factorial(n):
    if n == 1:
        return 1
    return n * factorial(n-1)

while True:
    num = sys.stdin.readline().strip()
    if num== '0':
        break    
    n = len(num)
    print(sum(map(lambda x : int(num[x])*factorial(n-x), range(n))))