# -*- coding: utf-8 -*-
"""[백준] Python 진법변환

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NXadrhdhpqIGMtYcyxG5GpM6H2Ar8mt2
"""

a1,b1=input().split()
b1=int(b1)
num='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'
result=0
for a in range(0,len(a1)):
  result+=num.index(a1[a])*(b1**(len(a1)-1-a))
print(result)