# -*- coding: utf-8 -*-
"""[프로그래머스] Python 비밀지도

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RVfL5EPbEHPfQUIw7QH-EfJu6VzNID5e
"""

n=5
arr1=[9, 20, 28, 18, 11]
arr2=[30, 1, 21, 17, 28]

answer=[]
for i,j in zip(arr1,arr2):
  tmp=str(bin(i|j)[2:])
  tmp=tmp.zfill(n)
  tmp=tmp.replace('1','#')
  tmp=tmp.replace('0',' ')
  answer.append(tmp)
print(answer)