# -*- coding: utf-8 -*-
"""#5 서울시 업무 추진비

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gz3LEt464I4wivF39rfpPtLavG5xd5Ic
"""

import pandas as pd
url='https://raw.githubusercontent.com/seoul-opengov/opengov/master/expense_list2021/202101_expense_list.csv'
s01=pd.read_csv(url)
url2='https://raw.githubusercontent.com/seoul-opengov/opengov/master/expense_list2021/202102_expense_list.csv'
s02=pd.read_csv(url2)

print(s01.shape)
print(s02.shape)

s2021=s01.append(s02)

s2021.shape

s2021['dept_nm_lvl_1'].unique()

s2021['dept_nm_lvl_1'].value_counts()

s2021['dept_nm_lvl_2'].unique()

s2021['dept_nm_lvl_2'].value_counts()

pd.describe_option()

pd.set_option('display.max_rows',200)

s2021['dept_nm_lvl_2'].value_counts()

s2021['exec_loc'].value_counts()



