# -*- coding: utf-8 -*-
"""복습#2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15fjkQUKdkbdsgSh3OoORM-aleS_R5raz
"""

!python -V

!uname

import random

def print_gugudan(n):
  for i in range(1,10):
    print(f"{n}*{i}={n*i}")

def print_gugudan(n):
  for i in range(1,10):
    print(f"{n}*{i}={n*i}")
print_gugudan(3)

## 위치인자
def pr(name,age):
## 기본인자
def pr(name,age=0):
##

def print_gugudan(start=0,end=0):
  if start==0 and end==0:
    for i in range(1,10): 
      print(f"{2}*{i}={2*i}")
  elif start==0 and end!=0:
    for j in range(2,end):
      for i in range(1,10): 
        print(f"{j}*{i}={j*i}")
  elif start!=0 and end==0:
    for j in range(start,10):
      for i in range(1,10): 
        print(f"{j}*{i}={j*i}")
  else:
    for j in range(start,end+1):
      for i in range(1,10): 
        print(f"{j}*{i}={j*i}")

print_gugudan(start=5)

# 한글 초중종성 분리 코드
  # 한글에서 초성분리
import re
  # 유니코드 한글 시작 : 44032, 끝 : 55199
BASE_CODE, CHOSUNG, JUNGSUNG = 44032, 588, 28
# 초성 리스트. 0 ~ 18
CHOSUNG_LIST = ['ㄱ', 'ㄲ', 'ㄴ', 'ㄷ', 'ㄸ', 'ㄹ', 'ㅁ', 'ㅂ', 'ㅃ', 'ㅅ', 'ㅆ', 'ㅇ', 'ㅈ', 'ㅉ', 'ㅊ', 'ㅋ', 'ㅌ', 'ㅍ', 'ㅎ']
# 중성 리스트. 0 ~ 20
JUNGSUNG_LIST = ['ㅏ', 'ㅐ', 'ㅑ', 'ㅒ', 'ㅓ', 'ㅔ', 'ㅕ', 'ㅖ', 'ㅗ', 'ㅘ', 'ㅙ', 'ㅚ', 'ㅛ', 'ㅜ', 'ㅝ', 'ㅞ', 'ㅟ', 'ㅠ', 'ㅡ', 'ㅢ', 'ㅣ']
# 종성 리스트. 0 ~ 27 + 1(1개 없음)
JONGSUNG_LIST = [' ', 'ㄱ', 'ㄲ', 'ㄳ', 'ㄴ', 'ㄵ', 'ㄶ', 'ㄷ', 'ㄹ', 'ㄺ', 'ㄻ', 'ㄼ', 'ㄽ', 'ㄾ', 'ㄿ', 'ㅀ', 'ㅁ', 'ㅂ', 'ㅄ', 'ㅅ', 'ㅆ', 'ㅇ', 'ㅈ', 'ㅊ', 'ㅋ', 'ㅌ', 'ㅍ', 'ㅎ']
  
def l(string):
  
    sp_list = list(string) # string make list
    result = []
    for keyword in sp_list:
    # 한글 여부 check 후 분리
      if re.match('.*[ㄱ-ㅎㅏ-ㅣ가-힣]+.*', keyword) is not None:
    # 초성
        char_code = ord(keyword) - BASE_CODE
        char1 = int(char_code / CHOSUNG)
        result.append(CHOSUNG_LIST[char1])
    
    return ("".join(result)) # 자소 분리 결과 출력

lines=''
with open('고사성어 1000개 모음.txt')as f:
  lines=f.readlines()
print('읽은 줄 수:',len(lines))

lines[13].split()

lines=''
with open('필수사자성어.txt')as f:
  lines=f.readlines()
print('읽은 줄 수:',len(lines))

li=[line.split()[1].split("(")[0] for line in lines]
hint=[line.split(":")[1] for line in lines]

li

hint=[line.split(":")[1] for line in lines]

hint

def get_se():
  lines=''
  with open('필수사자성어.txt')as f:
    lines=f.readlines()
  import random
  random_lno=random.randint(0,len(lines)-1)
  li=lines[random_lno].split()[1].split("(")[0]
  hint=lines[random_lno].split(":")[1]
  return (li,hint)



se

# 초성게임 코드
print("*** 초성게임 v0.1***")
print("*아래의 초성에 해당하는 사자성어를 입력하세요")

while True:
  se=get_se()
  ch=l(se[0])
  print('초성 : ',ch)
  print('힌트 : ',se[1])
  ans=input("사자성어를 입력 : ")
  if ans==se[0]:
    print('정답')
    break
  print('넌 바보')

!pip install gtts

