# -*- coding: utf-8 -*-
"""[프로그래머스]Python 괄호변환

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12mo90tyySWVp1T2NA0rIL-vTicndJKSm
"""

def solution(p):
    answer = ''
    return answer

## 재귀함수를 사용하는 문제인데.... 이걸 뭘 어떻게해야 잘 풀지?.. ㅠㅠ