# -*- coding: utf-8 -*-
"""[백준] DFS와 BFS

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pOw24Og5jOU7IkcuvzsteuXXzKFcURKY
"""

s=input()
N=int(s.split(" ")[0])
M=int(s.split(" ")[1])
V=int(s.split(" ")[2])
pg=[]
g=[]
for i in range(M):
  y=input()
  y.split("")[0]
  for k,v in enumerate(y):
    if k 
  g.append()
visited=[False]*N
def dfs(g,V,visited):
  visited[V]=True
  print(V,end='')
  for i in N-1:
    if !visited[i]:
      dfs(g,i,visited)

l=[]



