# -*- coding: utf-8 -*-
"""[프로그래머스]Python 정수 삼각형

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uB6HCTpLJBvb7HNMAJh2TXo7RCzryc33
"""

t=[[7], [3, 8], [8, 1, 0], [2, 7, 4, 4], [4, 5, 2, 6, 5]]
def solution(t):
  answer=0
  
  result=[ [] for i in range(len(t))]
  
  result[0].append(t[0]) # 0
  result[1].append(t[0][0]+t[1][0])
  result[1].append(t[0][0]+t[1][1]) # 1
  result[2].append(result[1][0]+t[2][0])
  result[2].append(max(result[1][0]+t[2][1],result[1][1]+t[2][1]))
  result[2].append(result[1][1]+t[2][2]) # 2

  for i in range(3,len(t)):
    for j in range(len(t[i])):
      if j==0:
        result[i].append(result[i-1][j]+t[i][j])
      elif j==len(t[i])-1:
        result[i].append(result[i-1][j-1]+t[i][j])
      else:
        result[i].append(max(result[i-1][j-1]+t[i][j], result[i-1][j]+t[i][j]))
  answer= max(result[-1])
  return answer

t=[[7], [3, 8], [8, 1, 0], [2, 7, 4, 4], [4, 5, 2, 6, 5]]
result=[ [] for i in range(len(t))]

result

solution(t)

result

