# -*- coding: utf-8 -*-
"""[프로그래머스] Python N으로 표현

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D-ETQ3CvllFlfQutphnBkp8UtPzPdnEo
"""

N=5
number=12
def solution(N, number):
    answer = -1
    dp = []
    
    for i in range (1,9) : 
        result = set()
        n2 = int(str(N)* i)
        result.add(n2)
        
        for j in range(0,i-1):
            for op1 in dp[j]:
                for op2 in dp[-j-1] :
                    result.add(op1 - op2)
                    result.add(op1 + op2)
                    result.add(op1 * op2)
                    if op2 != 0:
                        result.add(op1 // op2)
                        
        if number in result:
            answer = i
            break
            
        dp.append(result) 
        

    return answer

print(range(0,0))

for i in range(0,0):
  print(i)

