# -*- coding: utf-8 -*-
"""[프로그래머스] Python 전화번호 목록

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JWWxwQZGwTKfCL-gqHEc1inMQ6erawg3
"""

phone_book=["119", "97674223", "1195524421"]

def solution(phone_book):
    phone_book.sort()

    for i, j in zip(phone_book, phone_book[1:]):
        if j.startswith(i):
            return False
    return True

def solution(phone_book):
    answer = True
    hash_map = {}
    for phone_number in phone_book:
        hash_map[phone_number] = 1
    for phone_number in phone_book:
        temp = ""
        for number in phone_number:
            temp += number
            if temp in hash_map and temp != phone_number:
                answer = False
    return answer



