# -*- coding: utf-8 -*-
"""[프로그래머스] Python 완주하지 못한 선수.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/108HseyV-_YcVrJRBklLuPP5K_EEF-AR-
"""

participant=["leo", "kiki", "eden"]	
completion=["eden", "kiki"]

p=sorted(participant)
c=sorted(completion)

answer = ''

p

c

for i in range(len(c)):
    if p[i]!=c[i]:
      answer=p[i]
if answer=='':
  answer=p[len(p)-1]

answer

def solution(participant, completion):
  for i in range(len(c)):
    if p[i]!=c[i]:
      return p[i]
    
    return p[len(p)-1]

### 다른 답안
def solution(participant, completion):
    answer = ''
    temp = 0
    dic = {}
    for part in participant:
        dic[hash(part)] = part
        temp += int(hash(part))
    for com in completion:
        temp -= hash(com)
    answer = dic[temp]

    return answer

hash(p[1])

int(hash(p[1]))

