# -*- coding: utf-8 -*-
"""[프로그래머스] 타겟넘버

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UBmkKc1Xa-dLNvMusw9pVsvqN7a7a3xm
"""

def solution(numbers, target):
    def dfs(result,n):
        if n==len(numbers):
            if result==target:
                return 1
            return 0
        return dfs(result+numbers[n],n+1)+dfs(result-numbers[n],n+1)
    return dfs(0,0)