# -*- coding: utf-8 -*-
"""[백준] Python 해싱(Hashing).py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JWWxwQZGwTKfCL-gqHEc1inMQ6erawg3
"""

a1='abcdefghijklmnopqrstuvwxyz'
a2=a1.split(",")
b1=input()
b2=list(input())
a3=[a2.index(i)+1 for i in b2]
a4=[(31**j) for j in range(b1)]
answer=[i*j for i,j in zip(a3,a4)]
sum(answer)

a1='abcdefghijklmnopqrstuvwxyz'
b1=int(input())
b2=list(input())
a3=[(a1.index(i)+1)*(31**j) for i,j in zip(b2,range(b1))]
print(sum(a3)%1234567891)

a1='abcdefghijklmnopqrstuvwxyz'

for i,j in enumerate(b2):
  *(31**i)



