# -*- coding: utf-8 -*-
"""python_study_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zLEIVva9-3wlM1PCup1_gSH0mxM8427I
"""

##6-5