# -*- coding: utf-8 -*-
"""python_study.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cRnvPldSCZS_z0Hk_pZDc0_65Nhz-yGG
"""

##8

f=open(abc.txt,r)
lines=f.readlines()
f.close()
lines.reverse()
f=open('abc.txt','w')
for line in lines:
  line = line.strip()
  f.write(line)
  f.write('\n')
f.close

f=open('sample.txt','r')
lines=f.readlines()
f.close()
re=sum([i for i in lines])
re2=re/10

##10
class Calculator:
  def __init__(self,numberList):
    self.numberList = numberList

  def sum(self):
    return sum(self.numberList)

  def avg(self):
    return self.sum()/len(self.numberList)

cal1=Calculator([1,2,3])

cal1.sum()

cal1.avg()

##11

a=1+""

##14

def compress_string(s):
    _c = ""
    cnt = 0
    result = ""
    for c in s:
        if c!=_c:
            _c = c
            if cnt: result += str(cnt)
            result += c
            cnt = 1
        else:
            cnt +=1
    if cnt: result += str(cnt)
    return result
print(compress_string("aaabbcccccca"))

def con(s):
  result=[]
  for num in s:
    if num not in result:
      result.append(num)
    else:
      return False
  return len(result)==10
print(con("0123456789"))

s="0123456789 01234 01234567890 6789012345 012322456789"

a=s.split(" ")

a

dic = {
    '.-':'A','-...':'B','-.-.':'C','-..':'D','.':'E','..-.':'F',
    '--.':'G','....':'H','..':'I','.---':'J','-.-':'K','.-..':'L',
    '--':'M','-.':'N','---':'O','.--.':'P','--.-':'Q','.-.':'R',
    '...':'S','-':'T','..-':'U','...-':'V','.--':'W','-..-':'X',
    '-.--':'Y','--..':'Z'
}

def morse(s):
  result = []
  for word in s.split("  "):
    for char in word.split(" "):
      result.append(dic[char])
    result.append(" ")
  return "".join(result)
print(morse('.... .  ... .-.. . . .--. ...  . .- .-. .-.. -.--'))

