# -*- coding: utf-8 -*-
"""python_study_7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p53Hd0lkDRgCkF1UUni9inQCZ_TsXnob
"""

## 연습문제 5
## 피보나치 수열
def x(n):
  if n ==0:return 0
  if n==1: return 1
  return x(n-2)+x(n-1)
for i in range(10):
  print(x(i))

## 연습문제 6
user=input()
x=user.split(",")
total=[int(i) for i in x]

sum(total)

l = [i for i in range(1,10)]

l

x=int(input())
s=[x*i for i in l]
print(s)

f=open('abc.txt','r')
lines=f.readlines()
f.close()
lines.reverse()
f= open('abc.txt','w')
for line in lines:
  line = line.strip()
  f.write(line)
  f.write('\n')
f.close

f=open('sample.txt','r')
lines=f.readlines()
f.close()
sum=0
avg=0
cnt=0
for line in lines:
  cnt++
  sum+=int(line)
avg=sum/cnt
f=open('sample.txt','w')
f.write(str(avg))
f.close()

class Calculator:

  def __init__(self,num):
    self.num=num

  def add(self):
    result=sum(self.num)
    return result

  def avg(self):
    result=sum(self.num)/len(self.num)
    return result

cal1 = Calculator([1,2,3,4,5])

cal1.add()

cal1.avg()

[1,2,3][1]

def DashInsert(x):
  "*".join(x)
  
  for i in range(len(x)):
    while(i+2<=len(x)):
      if int(x[i])%2==0&int(x[i+2])%2!=0|int(x[i])%2!=0&int(x[i+2])%2==0:
        x[i+1].replace("*","")
      elif int(x[i])%2!=0&int(x[i+2])%2!=0:
        x[i+1].replace("*","-")
  return x

DashInsert("4546793")

