# -*- coding: utf-8 -*-
"""Python_study4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z7x5yuW58BYyF2fIJPdMuFRfmP0jdxmR
"""

class Calculator:
    def __init__(self):
        self.value = 0

    def add(self, val):
        self.value += val

class UpgradeCalculator(Calculator):
    def minus(self, val):
        self.value -= val

cal = UpgradeCalculator()
cal.add(10)
cal.minus(7)

print(cal.value)

class MaxLimitCalculator(Calculator):
   def add(self, val):
        self.value += val
        if self.value >100:
          self.value=100

cal = MaxLimitCalculator()
cal.add(50) # 50 더하기
cal.add(60) # 60 더하기

print(cal.value)

##4
print(list(filter(lambda x:x>0,[1, -2, 3, -5, 8, -3])))

##5
int('0xea',16)

##6
print(list(map(lambda x: x*3,[1, 2, 3, 4])))

##7
x=[-8, 2, 7, 5, -3, 5, 0, 1]

max(x)+min(x)

##8
round(17/3,4)

import sys

numbers = sys.argv[1:]
result = 0
for number in numbers:
    result += int(number)
print(result)

##10
import os
os.chdir("c:/doit")
result = os.popen("dir")
print(result.read())

##11
import glob
glob.glob("c:/doit/*.py")

import time
time.strftime("%Y/%m/%d %H:%M:%S")

import random

r=random

dir(r)

random.randint(1,45)

lotto=[i = random.randint(1,45) for i in range(6)]

##13
lotto=[]
for i in range(6):
  i=random.randint(1,45)
  lotto.append(i)

lotto

