# -*- coding: utf-8 -*-
"""Python_Study...1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UsOtXoe-gG6eXvp5KZBPicA9pq3tWEOn
"""

marks = [90, 25, 67, 45, 80]

number = 0 
for mark in marks: 
    number = number +1 
    if mark >= 60: 
        print("%d번 학생은 합격입니다." % number)
    else: 
        print("%d번 학생은 불합격입니다." % number)

marks = [90, 25, 67, 45, 80]
for number in range(len(marks)):
    if marks[number] < 60: 
        continue
    print("%d번 학생 축하합니다. 합격입니다." % (number+1))

range(5)

print(range(5))



n=1
result=0
while n<1001:
  if n%3==0:
    result+=n
  n+=1
result

n=1
while n<6:
  print("*"*n)
  n+=1

for i in range(1,101):
  print(i)

a=[70, 60, 55, 75, 95, 90, 80, 80, 85, 100]
sum=0
for i in a:
  sum+=i
print(sum/len(a))

numbers = [1, 2, 3, 4, 5]
result = []

result = [n*2 for n in numbers if n%2==1]

print(result)

a = 1
def vartest(a):
    a = a +1
    return a

print(vartest(a))
print(a)

a = 1 
def vartest(): 
    global a 
    a = a+1

vartest() 
print(a)

