# -*- coding: utf-8 -*-
"""[백준]Python 계단 오르기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KxRynWR2vONt-kVXRycURkA3xeKJ73eD
"""

x=input()

x

import sys
input = sys.stdin.readline
x=int(input())
data=[]
result=[]
for _ in range(x):
  data.append(int(input()))
if x==1:
  print(data[0])
  exit()
elif x == 2:
  print(max(data[0]+data[1], data[1]))
  exit()
  
result.append(data[0])
result.append(max(data[0]+data[1],data[1]))
result.append(max(data[0]+data[2],data[1]+data[2]))

for i in range(3,x):
  result.append(max(result[i-2]+data[i],result[i-3]+data[i-1]+data[i]))
print(result[-1])

t=[]
for i in range(3):
  t.append(i)

t

