# -*- coding: utf-8 -*-
"""[프로그래머스] Python 최단경로

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y1dAoBNmTWTnCjp9EojB5LlTqmUSjSa1
"""

