# -*- coding: utf-8 -*-
"""[백준] 바이러스

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15OQ_TFCOfXNhpkm6W2Uj58teWTmyxriu
"""

n=int(input())
e=int(input())
matrix=[[0]*(n+1) for i in range(n+1)]

visited=[False]*(n+1)
a=-1
for i in range(e):
  x,y=map(int,input().split())
  matrix[x][y]=matrix[y][x]=1
def dfs(v):
  global a
  visited[v]=True
  a+=1
  for i in range(1,n+1):
    if not visited[i] and matrix[v][i]==1:
      dfs(i)
  return a
print(dfs(1))